image: node:16

clone:
  depth: full

pipelines:
  branches:
    main:
    - step:
        name: Deploy to railway
        caches:
          - node
        deployment: production
        script:
          - npm i -g @railway/cli
          - RAILWAY_TOKEN=$RAILWAY_TOKEN railway up --service=$RAILWAY_SERVICE
